/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Link1Jacobian_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[16] = {2, 7, 0, 1, 2, 4, 6, 6, 6, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s3[14] = {2, 7, 0, 0, 0, 2, 4, 4, 4, 4, 0, 1, 0, 1};

/* Link1Jacobian:(i0[14],i1[2])->(o0[2x7,6nz],o1[2x7,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a6=sin(a1);
  a7=sin(a3);
  a8=(a6*a7);
  a5=(a5-a8);
  a5=(a0*a5);
  a8=arg[1]? arg[1][0] : 0;
  a9=cos(a1);
  a10=(a9*a7);
  a11=sin(a1);
  a12=(a11*a4);
  a10=(a10+a12);
  a10=(a8*a10);
  a5=(a5-a10);
  a10=1.9000000000000000e-001;
  a12=(a10*a7);
  a5=(a5-a12);
  if (res[0]!=0) res[0][2]=a5;
  a5=sin(a3);
  a12=(a2*a5);
  a13=cos(a3);
  a14=(a6*a13);
  a12=(a12+a14);
  a12=(a0*a12);
  a14=(a9*a13);
  a15=(a11*a5);
  a14=(a14-a15);
  a14=(a8*a14);
  a12=(a12+a14);
  a14=(a10*a13);
  a12=(a12+a14);
  a12=(-a12);
  if (res[0]!=0) res[0][3]=a12;
  a12=cos(a3);
  a14=cos(a1);
  a15=(a12*a14);
  a16=sin(a3);
  a17=sin(a1);
  a18=(a16*a17);
  a15=(a15-a18);
  a15=(a0*a15);
  a18=sin(a1);
  a19=(a12*a18);
  a20=cos(a1);
  a21=(a16*a20);
  a19=(a19+a21);
  a19=(a8*a19);
  a15=(a15-a19);
  if (res[0]!=0) res[0][4]=a15;
  a15=cos(a3);
  a19=(a15*a17);
  a21=sin(a3);
  a22=(a21*a14);
  a19=(a19+a22);
  a19=(a0*a19);
  a22=(a15*a20);
  a23=(a21*a18);
  a22=(a22-a23);
  a22=(a8*a22);
  a19=(a19+a22);
  a19=(-a19);
  if (res[0]!=0) res[0][5]=a19;
  a19=sin(a3);
  a22=(a2*a19);
  a23=cos(a3);
  a24=(a6*a23);
  a22=(a22+a24);
  a22=(a0*a22);
  a24=(a9*a23);
  a19=(a11*a19);
  a24=(a24-a19);
  a24=(a8*a24);
  a22=(a22+a24);
  a23=(a10*a23);
  a22=(a22+a23);
  a23=arg[0]? arg[0][9] : 0;
  a22=(a22*a23);
  a24=sin(a1);
  a19=(a4*a24);
  a25=cos(a1);
  a26=(a7*a25);
  a19=(a19+a26);
  a19=(a0*a19);
  a26=cos(a1);
  a4=(a4*a26);
  a27=sin(a1);
  a7=(a7*a27);
  a4=(a4-a7);
  a4=(a8*a4);
  a19=(a19+a4);
  a4=arg[0]? arg[0][10] : 0;
  a19=(a19*a4);
  a22=(a22+a19);
  a22=(-a22);
  if (res[1]!=0) res[1][0]=a22;
  a22=cos(a3);
  a2=(a2*a22);
  a19=sin(a3);
  a6=(a6*a19);
  a2=(a2-a6);
  a2=(a0*a2);
  a9=(a9*a19);
  a11=(a11*a22);
  a9=(a9+a11);
  a9=(a8*a9);
  a2=(a2-a9);
  a10=(a10*a19);
  a2=(a2-a10);
  a2=(a2*a23);
  a25=(a13*a25);
  a24=(a5*a24);
  a25=(a25-a24);
  a25=(a0*a25);
  a13=(a13*a27);
  a5=(a5*a26);
  a13=(a13+a5);
  a13=(a8*a13);
  a25=(a25-a13);
  a25=(a25*a4);
  a2=(a2+a25);
  a2=(-a2);
  if (res[1]!=0) res[1][1]=a2;
  a2=sin(a3);
  a25=(a14*a2);
  a13=cos(a3);
  a5=(a17*a13);
  a25=(a25+a5);
  a25=(a0*a25);
  a13=(a20*a13);
  a2=(a18*a2);
  a13=(a13-a2);
  a13=(a8*a13);
  a25=(a25+a13);
  a25=(a25*a23);
  a13=sin(a1);
  a2=(a12*a13);
  a5=cos(a1);
  a26=(a16*a5);
  a2=(a2+a26);
  a2=(a0*a2);
  a26=cos(a1);
  a12=(a12*a26);
  a1=sin(a1);
  a16=(a16*a1);
  a12=(a12-a16);
  a12=(a8*a12);
  a2=(a2+a12);
  a2=(a2*a4);
  a25=(a25+a2);
  a25=(-a25);
  if (res[1]!=0) res[1][2]=a25;
  a25=cos(a3);
  a14=(a14*a25);
  a3=sin(a3);
  a17=(a17*a3);
  a14=(a14-a17);
  a14=(a0*a14);
  a20=(a20*a3);
  a18=(a18*a25);
  a20=(a20+a18);
  a20=(a8*a20);
  a14=(a14-a20);
  a14=(a14*a23);
  a5=(a15*a5);
  a13=(a21*a13);
  a5=(a5-a13);
  a0=(a0*a5);
  a15=(a15*a1);
  a21=(a21*a26);
  a15=(a15+a21);
  a8=(a8*a15);
  a0=(a0-a8);
  a0=(a0*a4);
  a14=(a14+a0);
  a14=(-a14);
  if (res[1]!=0) res[1][3]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int Link1Jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Link1Jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Link1Jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Link1Jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Link1Jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Link1Jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Link1Jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void Link1Jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Link1Jacobian_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int Link1Jacobian_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Link1Jacobian_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Link1Jacobian_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Link1Jacobian_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Link1Jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Link1Jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Link1Jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
