/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int WB_FL2_terminal_constr(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int WB_FL2_terminal_constr_alloc_mem(void);
int WB_FL2_terminal_constr_init_mem(int mem);
void WB_FL2_terminal_constr_free_mem(int mem);
int WB_FL2_terminal_constr_checkout(void);
void WB_FL2_terminal_constr_release(int mem);
void WB_FL2_terminal_constr_incref(void);
void WB_FL2_terminal_constr_decref(void);
casadi_int WB_FL2_terminal_constr_n_out(void);
casadi_int WB_FL2_terminal_constr_n_in(void);
casadi_real WB_FL2_terminal_constr_default_in(casadi_int i);
const char* WB_FL2_terminal_constr_name_in(casadi_int i);
const char* WB_FL2_terminal_constr_name_out(casadi_int i);
const casadi_int* WB_FL2_terminal_constr_sparsity_in(casadi_int i);
const casadi_int* WB_FL2_terminal_constr_sparsity_out(casadi_int i);
int WB_FL2_terminal_constr_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
